Change newTramStop to TramStop
AelinaXY/tfgm pull request #3
Opened 2023-06-08 14:11 UTC by AelinaXY

2023-06-09 08:34 UTC, thomas-ayling commented on pom.xml
> +      <plugin>
You shouldn't need a dependency for Javadocs, support for them will be built into your IDE and you should find that nothing changes if you get rid of the dependencies

2023-06-09 08:34 UTC, thomas-ayling commented on src/main/java/com/tfgm/controllers/TramController.java
>    public TramController(String tramDataPath) throws IOException {
This business logic doesn't belong in the controller. Your controller should be used to defined endpoints in your API, but as it stands there are no endpoints defined. Consider moving you logic to a service layer.

2023-06-09 08:34 UTC, thomas-ayling commented on src/main/java/com/tfgm/controllers/TramController.java
> +      System.out.println(tramStop.toString());
I'd recommend using a logger instead of System.out before you get too far into the project

2023-06-09 08:34 UTC, thomas-ayling commented on src/main/java/com/tfgm/models/TramStop.java
> +  public void tramDeparture(String endOfLine) {
As discussed, try to keep data manipulations in the data layer, the model should serve as a representation of the data but not mutate it.

2023-06-09 08:34 UTC, thomas-ayling commented on src/main/java/com/tfgm/controllers/TramController.java
> +              if (tramStop != null) {
When moving your logic into the service layer, try to use more methods and variables with meaningful names to make sure the code is readable. At the moment it is quite difficult to decipher what is going on in the code.

2023-06-09 13:19 UTC, sourcesmith commented
Java.gitattributes should just be .gitattributes, by the way.  That repo had different files for different technologies.

2023-06-13 07:14 UTC, sourcesmith requested changes

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +    if (stopName == null) {
Is anything other than stop name and direction required for natural equality?

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +      if (!(tramStopContainer.getTramStop().getStopName().equals("Exchange Square"))
when comparing with a literal is better to `"string value".equals(...` ads this tolerates `null`s better.

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/controllers/TramController.java
> +  private final HashMap<String, TramStop> tramStopHashMap = new HashMap<>();
Collection types should be declared using the generic interface and not an implementation class. so `Map<String, TramStop> tramStopMap = ...`

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +  private final ArrayList<String> lastUpdated = new ArrayList<>();
Again, declare collections as the generic type.

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +    return nextStops;
You are return a reference to internal mutable state so violating encapsulation.

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +    return prevStops;
Violating encapsulation.

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +    return direction;
Suspect this can be an `Enum`.  Prefer strong types.

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +    return lastUpdated;
Violating encapsulation.

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +    if (tramQueue.size() > 0) {
`!tramQueue.isEmpty()` is more expressive.

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +        if (findEndOfLine(
`contain`s and `replace` is probably less work.

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +      if (tramStopContainer.getTramLinkStop().queueLength() > 0) {
`!` `isEmpty()`

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +  private final String direction;
Can be an `Enum`?

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +  private final ArrayList<String> lastUpdated = new ArrayList<>();
Prefer strong types so `OffsetDatetime` or` LocalDateTime` rather than string.

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +  private boolean findEndOfLine(String endOfLine, TramStop tramStop) {
Model lines as `Set`s of stops with associated terminal stops?

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +    this.prevStops = prevStops;
The object is being passed mutable collections which might have retained references thereby violating encapsulation.  Are the required so have not `null` assertions?

2023-06-13 07:14 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +    this.line = line;
Are these values really nullable.  Are empty and whitespace only strings allowed for instance?

2023-06-13 08:30 UTC, AelinaXY commented on src/main/java/com/tfgm/models/TramStop.java
> +  private final String direction;
Enum is probably better

2023-06-13 08:34 UTC, AelinaXY commented on src/main/java/com/tfgm/models/TramStop.java
> +  private final ArrayList<String> lastUpdated = new ArrayList<>();
The issue is that it comes from the API and then is combined with the destination so that it doesn't send a tram every time the api updates ~10s

2023-06-13 08:35 UTC, AelinaXY commented on src/main/java/com/tfgm/models/TramStop.java
> +    this.line = line;
Unsure what you're asking. Whitespace and empty would be allowed they just would never come up

2023-06-13 08:37 UTC, AelinaXY commented on src/main/java/com/tfgm/models/TramStop.java
> +    if (stopName == null) {
This is the auto-generated intelij equals method

2023-06-13 08:40 UTC, AelinaXY commented on src/main/java/com/tfgm/models/TramStop.java
> +    return nextStops;
Unsure how to resolve please help

2023-06-13 08:47 UTC, AelinaXY commented on src/main/java/com/tfgm/models/TramStop.java
> +  private boolean findEndOfLine(String endOfLine, TramStop tramStop) {
I'm unsure how that will improve / is a better solution than as a graph?

2023-06-13 09:18 UTC, AelinaXY commented on src/main/java/com/tfgm/models/TramStop.java
> +        if (findEndOfLine(
done

2023-06-13 09:18 UTC, AelinaXY commented on src/main/java/com/tfgm/models/TramStop.java
> +      if (tramStopContainer.getTramLinkStop().queueLength() > 0) {
done

2023-06-15 07:26 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +  private final ArrayList<String> lastUpdated = new ArrayList<>();
Is it effectively acting as complex key then?

2023-06-15 07:29 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +    this.line = line;
It normally to have checks on arguments for models and boundary layers validating or asserting constraints as appropriate.  This enforces method contracts and is an implementation of the fail fast principle rather than allowing errors to propagate in confusing and difficult to track down ways.

2023-06-15 07:30 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +    if (stopName == null) {
I believe IntelliJ displays a UI specifying which fields are to be included and `equals`/`hashcode` and whether they are nullable.

2023-06-15 07:48 UTC, sourcesmith commented on src/main/java/com/tfgm/models/TramStop.java
> +  private boolean findEndOfLine(String endOfLine, TramStop tramStop) {
Well, it is a graph.  What I mean is to avoid walking the graph to find out if a stop is on a certain line as this is not a dynamic property.  Or you could have a modified adjacency matrix with transitive adjacency to stops that intersect or terminate lines.

It is not a very big graph and so might not matter.  It depends at what rate it is being queried.  I am not saying anything is incorrect.  I suppose what I am trying to point out is the data structure might be analogue of the physical but data access patterns might be more important in  the long run.  So may be this comment falls in the realm of pre-mature optimisation.

2023-06-15 08:20 UTC, AelinaXY commented on src/main/java/com/tfgm/models/TramStop.java
> +  private final ArrayList<String> lastUpdated = new ArrayList<>();
effectively

2023-06-15 08:22 UTC, AelinaXY commented on src/main/java/com/tfgm/models/TramStop.java
> +    if (stopName == null) {
Makes sense, I've now updated that method

2023-06-29 14:28 UTC, merged